apiVersion: v1
kind: Pod
metadata:
  name: pproc-test-pod
  namespace: openfam
spec:
  schedulerName: default-scheduler
  containers:
    - name: launcher
      image: ghcr.io/opencube-horizon/pproc-benchmark@sha256:014330191acb3f67b0e38ce8f097d8b8f013e380284da45655c7f8a3f3bf909c
      command: ['/bin/sh', '-c', 'sleep infinity']
      env:
        - name: FI_PROVIDER
          value: cxi
        - name: CXIP_SKIP_AMA_CHECK
          value: 'true'
        - name: FI_CXI_LLRING_MODE
          value: never
        - name: OPENFAM_INSTALL_DIR
          value: '/usr/local/'
        - name: OPENFAM_ROOT
          value: '/usr/local/'
      volumeMounts:
        - name: libcxi
          readOnly: true
          mountPath: /usr/lib64/libcxi.so.1
        - name: cis
          mountPath: '/usr/local/config/fam_client_interface_config.yaml'
          subPath: 'fam_client_interface_config.yaml'
        - name: meta
          mountPath: '/usr/local/config/fam_metadata_config.yaml'
          subPath: 'fam_metadata_config.yaml'
        - name: mem
          mountPath: '/usr/local/config/fam_memoryserver_config.yaml'
          subPath: 'fam_memoryserver_config.yaml'
        - name: pe
          mountPath: '/usr/local/config/fam_pe_config.yaml'
          subPath: 'fam_pe_config.yaml'
      resources:
        requests:
          smarter-devices/cxi0: '1'
        limits:
          smarter-devices/cxi0: '1'
  volumes:
    - name: libcxi
      hostPath:
        path: /usr/lib64/libcxi.so.1
        type: File
    - name: cis
      configMap:
        name: openfam-cis
    - name: meta
      configMap:
        name: openfam-meta
    - name: mem
      configMap:
        name: openfam-mem
    - name: pe
      configMap:
        name: openfam-pe
  imagePullSecrets:
    - name: pproc-secret
  restartPolicy: Never
 
