out_keys:
  bitsPerValue: 12
members:
  end: 10
  start: 1
parameters:
  2t:
    targets: 
      out_efi: "%TARGET%"
      out_sot: "%TARGET%"    
    defs:
      base_keys: &base_keys_tp
        class: od
        domain: g
        expver: '0001'
        levtype: sfc
        param: 167
      base_interp: &base_interp_tp
        grid: 'O640'
        intgrid: none
        legendre-loader: shmem
        matrix-loader: file-io
      clim_steps: &clim_steps
        12-132: 0-120
        36-156: 24-144
        60-180: 48-168
        84-204: 72-192
        108-228: 96-216
        240-360: 240-360
    sources:
      fdb:
        ens:
          - <<: *base_keys_tp
            date: "%DATE%"
            time: 12
            stream: enfo
            type: cf
            interpolate: *base_interp_tp
          - <<: *base_keys_tp
            date: "%DATE%"
            time: 12
            stream: enfo
            type: pf
            interpolate: *base_interp_tp
        clim:
          <<: *base_keys_tp
          date: "%CLIM_DATE%"
          time: '00'
          stream: efhs
          type: cd
          param: 228004
          quantile: 100
          interpolate: *base_interp_tp
          step: *clim_steps
      fileset:
        ens:
          - <<: *base_keys_tp
            date: "%DATE%"
            time: 12
            stream: enfo
            type: cf
            location: "%LOCATION%"
          - <<: *base_keys_tp
            date: "%DATE%"
            time: 12
            stream: enfo
            type: pf
            location: "%LOCATION%"
        clim:
          <<: *base_keys_tp
          date: "%CLIM_DATE%"
          time: '00'
          stream: efhs
          type: cd
          param: 228004
          quantile: 100
          step: *clim_steps
          location: "%LOCATION%"
    eps: 1e-4
    sot:
    - 10
    - 90
    windows:
    - grib_set:
        edition: 1
        timeRangeIndicator: 3
        indicatorOfParameter: 167
        localDefinitionNumber: 19
        gribTablesVersionNo: 132
        mars.expver: '9078'
      periods:
      - range:
        - 12
        - 132
        - 6
      - range:
        - 36
        - 156
        - 6
      # - range:
      #   - 60
      #   - 180
      #   - 6
      # - range:
      #   - 84
      #   - 204
      #   - 6
      # - range:
      #   - 108
      #   - 228
      #   - 6
      # - range:
      #   - 240
      #   - 360
      #   - 6
      window_operation: mean
