out_keys:
  bitsPerValue: 12
members:
  end: 5
  start: 1
parameters:
  tp:
    targets: 
      out_efi: "fileset:cascade_extreme_{param}.grib"
      out_sot: "fileset:cascade_extreme_{param}.grib"
    efi_control: True
    defs:
      base_keys: &base_keys_tp
        class: od
        domain: g
        expver: '0001'
        levtype: sfc
        param: 228
      base_interp: &base_interp_tp
        grid: 'O640'
        intgrid: none
        legendre-loader: shmem
        matrix-loader: file-io
    sources:
      ens:
        - <<: *base_keys_tp
          date: 20230914
          time: 12
          stream: enfo
          type: cf
          interpolate: *base_interp_tp
          source: fdb
        - <<: *base_keys_tp
          date: 20230914
          time: 12
          stream: enfo
          type: pf
          interpolate: *base_interp_tp
          source: fdb
      clim:
        <<: *base_keys_tp
        date: '20230911'
        time: '00'
        stream: efhs
        type: cd
        quantile: 100
        interpolate: *base_interp_tp
        step:
          12-36: 0-24
          12-84: 0-72
          36-60: 24-48
        source: fdb
    eps: 1e-4
    sot:
    - 90
    windows:
    - grib_set:
        edition: 1
        gribTablesVersionNo: 132
        indicatorOfParameter: 228
        localDefinitionNumber: 19
        mars.expver: '9078'
        timeRangeIndicator: 5
        stepType: diff
      periods:
      - range:
        - 12
        - 36
        - 24
      - range:
        - 36
        - 60
        - 24
      - range:
        - 12
        - 84
        - 72
      window_operation: diff
      include_start_step: True
  capeshear:
    targets: 
      out_efi: "fileset:cascade_extreme_{param}.grib"
      out_sot: "fileset:cascade_extreme_{param}.grib"
    defs:
      base_keys: &base_keys_capeshear
        class: od
        domain: g
        expver: '0001'
        levtype: sfc
      base_interp: &base_interp_capeshear
        grid: 'O1280'
        intgrid: none
        legendre-loader: shmem
        matrix-loader: file-io
    sources:
      ens:
        - <<: *base_keys_capeshear
          stream: enfo
          type: cf
          date: 20230914
          time: 12
          param: [228036, 228035]
          interpolate: *base_interp_capeshear
          source: fdb
        - <<: *base_keys_capeshear
          stream: enfo
          type: pf
          date: 20230914
          time: 12
          param: [228036, 228035]
          interpolate: *base_interp_capeshear
          source: fdb
      clim:
        <<: *base_keys_capeshear
        date: '20230911'
        time: '00'
        param: 228044
        stream: efhs
        type: cd
        quantile: 100
        interpolate: *base_interp_capeshear
        source: fdb
        step:
          12-36: 0-24
    eps: 1e-4
    input_filter_operation:
      comparison: <=
      threshold: 10
    sot:
    - 90
    windows:
    - grib_set:
        param: 228035
        typeOfStatisticalProcessing: 1
        edition: 1
        indicatorOfTypeOfLevel: 1
        timeRangeIndicator: 2
        indicatorOfParameter: 44
        gribTablesVersionNo: 132
        localDefinitionNumber: 19
        mars.expver: '9078'
      periods:
      - range:
        - 12
        - 36
        - 6
      window_operation: maximum