out_keys:
  bitsPerValue: 12
members:
  end: 50
  start: 1
parameters:
  2t:
    targets: 
      out_efi: "fileset:cascade_extreme_{param}.grib"
      out_sot: "fileset:cascade_extreme_{param}.grib"
    defs:
      base_keys: &base_keys_tp
        class: od
        domain: g
        expver: '0001'
        levtype: sfc
        param: 167
      base_interp: &base_interp_tp
        grid: 'O640'
        intgrid: none
        legendre-loader: shmem
        matrix-loader: file-io
    sources:
      ens:
        - <<: *base_keys_tp
          date: 20230914
          time: 12
          stream: enfo
          type: cf
          interpolate: *base_interp_tp
          source: fdb
        - <<: *base_keys_tp
          date: 20230914
          time: 12
          stream: enfo
          type: pf
          interpolate: *base_interp_tp
          source: fdb
      clim:
        <<: *base_keys_tp
        date: '20230911'
        time: '00'
        stream: efhs
        type: cd
        param: 228004
        quantile: 100
        interpolate: *base_interp_tp
        step:
          12-36: 0-24
          36-60: 24-48
          60-84: 48-72
          84-108: 72-96
          108-132: 96-120
          132-156: 120-144
          156-180: 144-168
          180-204: 168-192
          204-228: 192-216
          240-264: 240-264
          264-288: 264-288
          264-288: 264-288
          288-312: 288-312
          312-336: 312-336
          336-360: 336-360
        source: fdb
    eps: 1e-4
    sot:
    - 10
    - 90
    windows:
    - grib_set:
        edition: 1
        timeRangeIndicator: 3
        indicatorOfParameter: 167
        localDefinitionNumber: 19
        gribTablesVersionNo: 132
        mars.expver: '9078'
      periods:
      - range:
        - 12
        - 36
        - 6
      - range:
        - 36
        - 60
        - 6
      - range:
        - 60
        - 84
        - 6
      - range:
        - 84
        - 108
        - 6
      - range:
        - 108
        - 132
        - 6
      - range:
        - 132
        - 156
        - 6
      - range:
        - 156
        - 180
        - 6
      - range:
        - 180
        - 204
        - 6
      - range:
        - 204
        - 228
        - 6
      - range:
        - 240
        - 264
        - 6
      - range:
        - 264
        - 288
        - 6
      - range:
        - 288
        - 312
        - 6
      - range:
        - 312
        - 336
        - 6
      - range:
        - 336
        - 360
        - 6
      window_operation: mean