out_keys:
  bitsPerValue: 12
members:
  end: 50
  start: 1
parameters:
  2t:
    targets: 
      out_efi: "fileset:cascade_extreme_{param}.grib"
      out_sot: "fileset:cascade_extreme_{param}.grib"
    defs:
      base_keys: &base_keys_tp
        class: od
        domain: g
        expver: '0001'
        levtype: sfc
        param: 167
      base_interp: &base_interp_tp
        grid: 'O640'
        intgrid: none
        legendre-loader: shmem
        matrix-loader: file-io
    sources:
      ens:
        - <<: *base_keys_tp
          date: 20230914
          time: 12
          stream: enfo
          type: cf
          interpolate: *base_interp_tp
          source: fdb
        - <<: *base_keys_tp
          date: 20230914
          time: 12
          stream: enfo
          type: pf
          interpolate: *base_interp_tp
          source: fdb
      clim:
        <<: *base_keys_tp
        date: '20230911'
        time: '00'
        stream: efhs
        type: cd
        param: 228004
        quantile: 100
        interpolate: *base_interp_tp
        step:
          12-132: 0-120
          36-156: 24-144
          60-180: 48-168
          84-204: 72-192
          108-228: 96-216
          240-360: 240-360
        source: fdb
    eps: 1e-4
    sot:
    - 10
    - 90
    windows:
    - grib_set:
        edition: 1
        timeRangeIndicator: 3
        indicatorOfParameter: 167
        localDefinitionNumber: 19
        gribTablesVersionNo: 132
        mars.expver: '9078'
      periods:
      - range:
        - 12
        - 132
        - 6
      - range:
        - 36
        - 156
        - 6
      - range:
        - 60
        - 180
        - 6
      - range:
        - 84
        - 204
        - 6
      - range:
        - 108
        - 228
        - 6
      - range:
        - 240
        - 360
        - 6
      window_operation: mean